### ISSUE TITLE
Code for downstream task evaluation

### ISSUE THREAD

**Issue by priyankamandikal** [facebookresearch/vip#2]
Hi, could you share the evaluation code for testing this pretrained representation on downstream tasks?

**Comment by JasonMa2016** [comment]
Hi! Thank you for your interests in our work! We are planning on releasing the code for the trajectory optimization experiments in the next week or so. Stay tuned!

**Comment by JasonMa2016** [comment]
Thank you for your patience. I have added the code to run our trajectory optimization experiment in the paper. it's under the `eval` branch. Please let me know if it works for you!
