### ISSUE TITLE
Download does not catch missing config file

### ISSUE THREAD

**Issue by kpertsch** [facebookresearch/vip#6]
Thanks for the great work Jason!

One small problem I encountered: the `load_vip()` function has an `except` statement in case the initial download from pyhub fails. However, this function fails to catch scenarios in which the model was downloaded but an error occurs before the config was downloaded, because it only checks `if not os.path.exists(modelpath): ...` 

In my case, I tried installing on a CPU-only machine and the model download errored out because it by default tries to load the state dict onto GPU. Wouldn't be a problem if it then resorted to loading the config from `gdown`, but it instead skips the gdown fallback and errors out after because the config is missing.

Easy fix is to use `if not os.path.exists(configpath): ...` before the line that runs gdown for the config file: https://github.com/facebookresearch/vip/blob/676d24ce08e76475595c9a0167d1fdfdd1da5624/vip/__init__.py#L61

This way it will always download the config if it's still missing.
After this change `load_vip()` works for me.

**Comment by JasonMa2016** [comment]
Hi Karl, thanks for catching this bug! I just pushed the corrected version.
